// =============================================================================
// CarGo — Full Project Context
// =============================================================================
// Single source of truth for the project's architecture, patterns, and rules.
// Read this at the start of any new session / after a token reset before
// making any changes to the project.
// Keep this file updated whenever structure, patterns, or rules change.
// =============================================================================

// ignore_for_file: unused_element

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 1 — FOLDER STRUCTURE
// ─────────────────────────────────────────────────────────────────────────────
//
// lib/
// ├── main.dart
// │     Entry point. Initialises Firebase, ScreenUtil, PreferencesManager.
// │     Wraps the app in ScreenUtilInit (design 375×832) + lightTheme.
// │     Home is SplashScreen.
// │
// ├── firebase_options.dart          Auto-generated by FlutterFire CLI.
// │
// ├── models/
// │   ├── car_model.dart             Car — fromJson / toJson
// │   ├── review_model.dart          Review — fromJson
// │   └── booking_model.dart         Booking — fromMap / toMap
// │
// ├── services/
// │   └── services_screen.dart       Placeholder: "Services are under development"
// │
// ├── core/
// │   ├── constants/
// │   │   ├── app_size.dart          AppSizes — responsive sizes via ScreenUtil
// │   │   └── project_context.dart   ← THIS FILE
// │   ├── dataSource/
// │   │   ├── local_data/
// │   │   │   └── preferences_manager.dart   Singleton SharedPreferences
// │   │   └── remote_data/
// │   │       └── firebase_service.dart       Singleton — Auth + Firestore + Storage
// │   ├── theme/
// │   │   ├── light_color.dart       LightColors constants
// │   │   └── light_theme.dart       lightTheme ThemeData
// │   └── widgets/
// │       ├── custom_cached_network_image.dart
// │       ├── custom_svg_picture..dart
// │       ├── custom_text_formField.dart
// │       ├── location_sheet.dart    Modal bottom sheet — city list → String
// │       └── search_widget.dart     Tied to HomeController — do not embed elsewhere
// │
// └── Features/
//     ├── Main/main_screen.dart      BottomNavigationBar hub (5 tabs)
//     ├── splash/splash_screen.dart
//     ├── auth/
//     │   ├── controllers/login_controller.dart
//     │   ├── controllers/otp_controller.dart
//     │   ├── controllers/signup_controller.dart
//     │   ├── login_screen.dart
//     │   ├── otp_screen.dart
//     │   └── siginup_screen.dart
//     ├── home/
//     │   ├── controllers/home_controller.dart
//     │   ├── home_screen.dart
//     │   └── widgets/car_card.dart
//     ├── details/
//     │   ├── controllers/car_details_controller.dart
//     │   └── car_details_screen.dart   Book Now → BookingScreen
//     ├── booking/
//     │   ├── booking_controller.dart   Provider — auth guard + Firestore
//     │   └── booking_screen.dart       Date/time pickers + price + Continue
//     ├── search/
//     │   ├── controller/search_controller.dart   Direct Firestore usage
//     │   ├── presentation/search_screen.dart
//     │   └── widgets/ (search_bar_widget, search_filter_panel, search_header)
//     ├── profile/presentation/profile_screen.dart
//     ├── cites/presentation/cities_screen.dart
//     ├── chats/presentation/chats_screen.dart
//     └── reviews/reviews_screen.dart

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 2 — THEME SYSTEM
// ─────────────────────────────────────────────────────────────────────────────
//
// FILE: lib/core/theme/light_color.dart
//
//   class LightColors {
//     static const Color primaryColor    = Color(0xFF004B09);  // dark green
//     static const Color backgroundColor = Color(0xFFF6F7F9);  // light grey-white
//     static const Color textColor       = Color(0xFF0D0D0D);  // near-black
//   }
//
// Always use LightColors constants. Never hardcode colours.
//
// FILE: lib/core/theme/light_theme.dart
//
//   lightTheme = ThemeData(
//     useMaterial3: true,
//     scaffoldBackgroundColor: Color(0xFFf5f5f5),
//     primaryColor: LightColors.primaryColor,
//     colorScheme: ColorScheme.light(primary: LightColors.primaryColor),
//     appBarTheme: AppBarTheme(
//       backgroundColor: Colors.white,
//       titleTextStyle: TextStyle(fontSize: 16sp, fontWeight: w700),
//     ),
//     elevatedButtonTheme: ElevatedButtonThemeData(
//       style: ElevatedButton.styleFrom(
//         backgroundColor: LightColors.primaryColor,
//         minimumSize: Size.fromHeight(52h),
//         shape: RoundedRectangleBorder(borderRadius: BorderRadius.zero),
//       ),
//     ),
//     inputDecorationTheme: InputDecorationTheme(
//       filled: true, fillColor: Colors.white,
//       focusedBorder/enabledBorder: OutlineInputBorder(Color(0xFFD1DAD6), 0.5px),
//     ),
//     bottomNavigationBarTheme: BottomNavigationBarThemeData(
//       backgroundColor: Color(0xFFB5B3B3),
//       selectedItemColor: LightColors.primaryColor,
//     ),
//   );
//
// Override button shape per screen using ElevatedButton.styleFrom(shape: ...).

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 3 — STATE MANAGEMENT (Provider)
// ─────────────────────────────────────────────────────────────────────────────
//
// Provider (^6.1.1) is the only state management library. No Riverpod, Bloc,
// GetX, or any other library is used or should be introduced.
//
// ── Screen pattern ────────────────────────────────────────────────────────────
//
//   class MyScreen extends StatelessWidget {
//     @override
//     Widget build(BuildContext context) {
//       return ChangeNotifierProvider(
//         create: (_) => MyController(),
//         child: Builder(
//           builder: (context) {
//             final ctrl = context.watch<MyController>(); // reactive
//             return Scaffold(
//               body: GestureDetector(
//                 onTap: () => context.read<MyController>().doSomething(),
//                 // context.read() in callbacks — does NOT subscribe
//               ),
//             );
//           },
//         ),
//       );
//     }
//   }
//
// ── Controller pattern ────────────────────────────────────────────────────────
//
//   class MyController extends ChangeNotifier {
//     bool _isLoading = false;
//     String? _error;
//
//     bool get isLoading => _isLoading;
//     String? get error => _error;
//
//     Future<void> fetchData() async {
//       _isLoading = true; _error = null; notifyListeners();
//       try {
//         // ...
//       } catch (e) {
//         _error = e.toString();
//       } finally {
//         _isLoading = false; notifyListeners();
//       }
//     }
//   }
//
// Rules:
//   - Every controller extends ChangeNotifier.
//   - Every screen wraps with its own ChangeNotifierProvider.
//   - context.watch<>() → reactive, inside build only.
//   - context.read<>() → non-reactive, inside callbacks only.

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 4 — NAVIGATION
// ─────────────────────────────────────────────────────────────────────────────
//
//   Navigator.push(context, MaterialPageRoute(builder: (_) => TargetScreen()));
//   Navigator.pushReplacement(context, MaterialPageRoute(...));
//   Navigator.pushAndRemoveUntil(context, MaterialPageRoute(...), (_) => false);
//   Navigator.pop(context);
//
// Rules:
//   - No named routes anywhere.
//   - Always MaterialPageRoute with a direct class reference.
//   - Back button always uses Navigator.pop(context).

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 5 — FIRESTORE USAGE
// ─────────────────────────────────────────────────────────────────────────────
//
// Two approaches — do not mix within the same controller:
//
// A) FirebaseService singleton — shared operations (login, getCars, getReviews).
//      await FirebaseService().getCars();
//
// B) Direct FirebaseFirestore.instance — feature-specific queries.
//      Used in: SearchCarController, BookingController.
//      final _firestore = FirebaseFirestore.instance;
//      final snap = await _firestore.collection('bookings').where(...).get();
//
// RULE: Do NOT create a separate service file for new features.
//       All Firestore logic lives inside the controller (approach B).
//
// ── Collections ───────────────────────────────────────────────────────────────
//
//   Name       Purpose
//   ────────   ─────────────────────────────────────────────────────────────
//   users      User profiles
//   cars       Car listings (includes availableFrom / availableTo)
//   Reviews    Car reviews — capital R in Firestore
//   bookings   Booking records
//
// ── Timestamp handling ────────────────────────────────────────────────────────
//   Always guard DateTime fields with `is Timestamp` before calling .toDate():
//
//     createdAt: json['createdAt'] is Timestamp
//         ? (json['createdAt'] as Timestamp).toDate()
//         : DateTime.now(),

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 6 — HOW FIRESTORE SECURITY RULES WORK
// ─────────────────────────────────────────────────────────────────────────────
//
// Firestore Security Rules are evaluated SERVER-SIDE by Google's infrastructure,
// not inside the Flutter app. The rules run for every Firestore request and
// decide whether to allow or deny it before any data is returned.
//
// How a request is evaluated:
//   1. The app sends a Firestore query (e.g. .collection('bookings').get()).
//   2. Firebase validates the user's auth token attached to the request.
//   3. Firebase runs the matching Security Rule against the request.
//   4. If the rule evaluates to false → PERMISSION_DENIED is returned.
//   5. If the rule evaluates to true → the data is returned.
//
// For QUERIES (multiple documents), Firestore evaluates the rule against
// every document in the result set. If ANY document fails the rule,
// the entire query is denied.
//
// No Dart-side code can bypass or override server-side rules.
// The isAuthenticated check in the controller prevents sending requests
// when there is no local session, but it cannot change how the server
// evaluates the rules once the request is received.

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 7 — WHY AUTHENTICATED USERS STILL GET PERMISSION_DENIED
// ─────────────────────────────────────────────────────────────────────────────
//
// ── The specific scenario in this project ────────────────────────────────────
//
// BookingController._hasOverlap() queries:
//   _firestore.collection('bookings').where('carId', isEqualTo: car.id).get()
//
// This returns ALL booking documents for a car — including bookings created
// by OTHER users (different userId values).
//
// If the Firestore rule for bookings is:
//   allow read: if request.auth.uid == resource.data.userId;
//
// ...then for each returned document, Firestore checks whether the requester's
// UID matches the userId field stored inside that booking document.
//
// For bookings that belong to user A, and the request comes from user B:
//   request.auth.uid = "uid_of_user_B"
//   resource.data.userId = "uid_of_user_A"
//   result: false → PERMISSION_DENIED
//
// The user is fully authenticated. The error is NOT about missing login.
// The error is that the rules only allow users to read THEIR OWN bookings,
// but the overlap check must read EVERYONE'S bookings for a given car.
//
// ── Why this rule design is wrong for our use case ────────────────────────────
//
// Bookings belong to CARS, not just users. To determine if a car is available
// for new dates, we must read all existing bookings for that car — regardless
// of which user made them. The rule must therefore allow any authenticated
// user to read any booking:
//
//   allow read: if request.auth != null;    ← CORRECT for our use case
//
// vs.
//
//   allow read: if request.auth.uid == resource.data.userId;  ← WRONG — blocks
//                                                                cross-user reads
//
// ── The symptom ───────────────────────────────────────────────────────────────
//
// In the Android/iOS log:
//   W/Firestore: Listen for Query(target=Query(bookings where carId==XXX
//               order by __name__);limitType=LIMIT_TO_FIRST) failed:
//               Status{code=PERMISSION_DENIED, description=Missing or
//               insufficient permissions., cause=null}
//
// The word "Listen" is Firestore's internal mechanism — both .get() and
// .snapshots() use a listener internally. The carId in the log confirms
// it is our overlap check query.
//
// ── How BookingController handles it ─────────────────────────────────────────
//
//   1. isAuthenticated is checked first — stops the request if no local session.
//   2. If a FirebaseException with code 'permission-denied' is caught:
//      - _firestoreRulesError is set to true.
//      - BookingScreen displays a persistent red banner with the exact fix.
//      - A SnackBar is also shown.
//
// ─────────────────────────────────────────────────────────────────────────────
// SECTION 8 — RECOMMENDED FIRESTORE SECURITY RULES
// ─────────────────────────────────────────────────────────────────────────────
//
// Set these in: Firebase Console → Firestore Database → Rules
// Do NOT apply them from code — they are configured only in the Firebase Console.
//
// ════════════════════════════════════════════════════════════════════════════
// rules_version = '2';
// service cloud.firestore {
//   match /databases/{database}/documents {
//
//     // Users — only the owner reads/writes their own profile
//     match /users/{userId} {
//       allow read, write: if request.auth != null
//                          && request.auth.uid == userId;
//     }
//
//     // Cars — public reads, authenticated writes
//     match /cars/{carId} {
//       allow read: if true;
//       allow write: if request.auth != null;
//     }
//
//     // Reviews — public reads, authenticated writes
//     match /Reviews/{reviewId} {
//       allow read: if true;
//       allow write: if request.auth != null;
//     }
//
//     // Bookings
//     //
//     // allow read: if request.auth != null;
//     //   ↑ REQUIRED. Any authenticated user must be able to read all bookings.
//     //   The overlap check queries bookings by carId across all users.
//     //   Using resource.data.userId == request.auth.uid here would block that
//     //   query and cause PERMISSION_DENIED even for logged-in users.
//     //
//     // allow write: if request.auth != null;
//     //   ↑ Any authenticated user can write. You may tighten this to
//     //   request.resource.data.userId == request.auth.uid if needed.
//     //
//     match /bookings/{bookingId} {
//       allow read:  if request.auth != null;
//       allow write: if request.auth != null;
//     }
//   }
// }
// ════════════════════════════════════════════════════════════════════════════

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 9 — MODELS
// ─────────────────────────────────────────────────────────────────────────────
//
// All models: lib/models/. Plain Dart classes — no codegen, no annotations.
//
// Car (car_model.dart) — import: cloud_firestore
//   Fields: id, brand, model, location, overview, ownerId, transmission (String)
//           available, isElectric (bool)
//           km, pricePerDay, rating (double)
//           reviewsCount, seats, year (int)
//           images (List<String>)
//           ownerName?, ownerImage? (String?)
//           availableFrom?, availableTo? (DateTime?) ← rental availability window
//   Methods: fromJson(Map) / toJson() → Map
//
// Review (review_model.dart) — import: cloud_firestore
//   Fields: id, carId, userId, comment (String)
//           rating (double)
//           createdAt? (DateTime)
//           userName?, userImage? (String?) — mutable, filled post-fetch
//   Methods: fromJson(Map)
//
// Booking (booking_model.dart) — import: cloud_firestore
//   Fields: bookingId, userId, carId, pickupTime (String)
//           status: 'pending' | 'confirmed' | 'cancelled'
//           startDate, endDate, createdAt (DateTime)
//           totalPrice (double)
//   Methods: fromMap(Map) / toMap() → Map

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 10 — BOOKING FEATURE
// ─────────────────────────────────────────────────────────────────────────────
//
// Flow:
//   CarDetailsScreen → (Book Now) → BookingScreen → (Continue) → ServicesScreen
//
// BookingController — lib/Features/booking/booking_controller.dart
//   No separate BookingService file. Follows SearchCarController pattern.
//
//   State:
//     _startDate, _endDate (DateTime?)
//     _pickupTime (TimeOfDay?)
//     _isLoading (bool)
//     _error (String?)
//     _firestoreRulesError (bool) ← true when Firestore returns permission-denied
//
//   isAuthenticated: FirebaseAuth.instance.currentUser != null
//     → Checked before EVERY Firestore call.
//
//   createBooking() execution order (MUST NOT CHANGE):
//     1. isAuthenticated    — stops the request if not logged in
//     2. _validate()        — local only: dates, time, availability window
//     3. _hasOverlap()      — Firestore READ by carId (reads other users' bookings)
//     4. _firestore.set()   — Firestore WRITE
//
//   Error handling:
//     FirebaseException code 'permission-denied' → sets _firestoreRulesError = true
//     BookingScreen shows a red inline banner with the exact fix.
//
// BookingScreen — lib/Features/booking/booking_screen.dart
//   - !ctrl.isAuthenticated → Login Required wall (Log In button → LoginScreen)
//   - ctrl.firestoreRulesError → Red banner explaining the Firestore rules issue
//   - Date pickers styled identically to SearchWidget (same colours and radii)
//   - SearchWidget is NOT embedded — it is tightly coupled to HomeController
//   - Shows availability window banner if car.availableFrom/To are set
//   - Shows price summary when dates are selected
//   - Continue → ctrl.createBooking() → on success → ServicesScreen

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 11 — REUSABLE CORE WIDGETS
// ─────────────────────────────────────────────────────────────────────────────
//
// SearchWidget (lib/core/widgets/search_widget.dart)
//   Reads from HomeController via context.watch<HomeController>().
//   Contains: pick-up location pill, date range pill, Search button.
//   Container: bg Color(0xFFCFCFCF), border Color(0xFF9E9E9E) 1.5px, radius 16.
//   Pill:      bg Color(0xFFBDBDBD), radius 10.
//   RULE: Never embed outside HomeScreen. Replicate style manually elsewhere.
//
// LocationSheet (lib/core/widgets/location_sheet.dart)
//   Modal bottom sheet. Returns selected city String.
//   Background Color(0xFFD4D4D4), top corners radius 20.

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 12 — NAMING CONVENTIONS
// ─────────────────────────────────────────────────────────────────────────────
//
//   Element          Convention        Example
//   ──────────────   ──────────────    ───────────────────────
//   File             snake_case        booking_screen.dart
//   Class            PascalCase        BookingController
//   Screen class     *Screen           BookingScreen
//   Controller       *Controller       BookingController
//   Widget           *Widget / noun    SearchWidget, CarCard
//   Model class      singular noun     Car, Review, Booking
//   Private field    _camelCase        _isLoading, _startDate
//   Public getter    camelCase         isLoading, startDate
//   Private method   _camelCase        _validate(), _hasOverlap()
//   Section comment  // ── Name ───    // ── State ──────────────

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 13 — ARCHITECTURAL RULES
// ─────────────────────────────────────────────────────────────────────────────
//
//  1. Provider only — no Riverpod, Bloc, GetX, or any other state library.
//  2. No named routes — always MaterialPageRoute with a direct class reference.
//  3. No service files for new features — Firestore logic stays in the controller.
//  4. Auth check FIRST before any Firestore call in a protected controller.
//  5. SearchWidget is coupled to HomeController — never embed it outside HomeScreen.
//  6. Firestore Timestamps — always guard with `is Timestamp` before .toDate().
//  7. User-facing errors — always via ScaffoldMessenger.showSnackBar().
//  8. Loading state — CircularProgressIndicator(color: LightColors.primaryColor).
//  9. Section comments — use style: // ── Name ─────────────────────────────
// 10. No speculative abstractions — add only what the current task requires.
// 11. FirebaseException caught separately from Exception — code 'permission-denied'
//     surfaces a specific message; other codes surface a generic one.
// 12. _firestoreRulesError flag in BookingController drives a persistent inline
//     banner in BookingScreen (not just a transient SnackBar).

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 14 — PACKAGES
// ─────────────────────────────────────────────────────────────────────────────
//
//   Package                 Version    Purpose
//   ───────────────────     ────────   ──────────────────────────────────────
//   flutter_screenutil      ^5.9.0     Responsive sizing (.sp .h .w .r)
//   provider                ^6.1.1     State management
//   firebase_core           latest     Firebase initialisation
//   firebase_auth           latest     Authentication
//   cloud_firestore         latest     Database
//   firebase_storage        latest     File storage
//   cached_network_image    latest     Network image caching with shimmer
//   shimmer                 latest     Loading placeholder
//   flutter_svg             latest     SVG asset rendering
//   shared_preferences      latest     Local key-value persistence
//
//   ScreenUtil design size: 375 × 832

abstract final class ProjectContext {}